"""Managed application-window contract; IDs are opaque, never browser targets."""

from typing import Protocol


class ApplicationWindowPort(Protocol):
    def open_count(self) -> int: ...

    def window_for_task(self, task_id: str) -> str | None: ...

    def exists(self, window_id: str) -> bool: ...

    def allocate(self, task_id: str) -> str: ...

    def release(self, window_id: str) -> None: ...

    def bring_to_front(self, window_id: str) -> None: ...
